-- MySQL Script generated by MySQL Workbench
-- Sat Sep 17 12:30:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8 ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Estado` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NOT NULL,
  `Descripcion` VARCHAR(255) NOT NULL,
  `FechaCreacion` DATETIME NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Categoria` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NOT NULL,
  `Descripcion` VARCHAR(255) NOT NULL,
  `Codigo` VARCHAR(45) NOT NULL,
  `FechaCreacion` DATETIME NOT NULL,
  `Estado` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Categoria_Estado_idx` (`Estado` ASC) VISIBLE,
  CONSTRAINT `fk_Categoria_Estado`
    FOREIGN KEY (`Estado`)
    REFERENCES `ecommerce`.`Estado` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Marca` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NOT NULL,
  `Descripcion` VARCHAR(255) NOT NULL,
  `FechaCreacion` DATETIME NOT NULL,
  `Estado` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Marca_Estado1_idx` (`Estado` ASC) VISIBLE,
  CONSTRAINT `fk_Marca_Estado1`
    FOREIGN KEY (`Estado`)
    REFERENCES `ecommerce`.`Estado` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Descuento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Descuento` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NOT NULL,
  `Codigo` VARCHAR(255) NOT NULL,
  `ValorPorcentaje` DECIMAL(10) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Producto` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(225) NOT NULL,
  `PrecioVenta` DECIMAL(10) NOT NULL,
  `Stock` INT NOT NULL,
  `PrecioCompra` DECIMAL(10) NOT NULL,
  `Imagen` TEXT(1000) CHARACTER SET 'armscii8' NOT NULL,
  `FechaCreacion` DATETIME NOT NULL,
  `Estado` INT NOT NULL,
  `Marca` INT NOT NULL,
  `Categoria` INT NOT NULL,
  `Descuento` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Producto_Estado1_idx` (`Estado` ASC) VISIBLE,
  INDEX `fk_Producto_Marca1_idx` (`Marca` ASC) VISIBLE,
  INDEX `fk_Producto_Categoria1_idx` (`Categoria` ASC) VISIBLE,
  INDEX `fk_Producto_Descuento1_idx` (`Descuento` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Estado1`
    FOREIGN KEY (`Estado`)
    REFERENCES `ecommerce`.`Estado` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Marca1`
    FOREIGN KEY (`Marca`)
    REFERENCES `ecommerce`.`Marca` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Categoria1`
    FOREIGN KEY (`Categoria`)
    REFERENCES `ecommerce`.`Categoria` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Descuento1`
    FOREIGN KEY (`Descuento`)
    REFERENCES `ecommerce`.`Descuento` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
