-- MySQL Script generated by MySQL Workbench
-- Sat Sep 17 12:02:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema pointsales
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pointsales
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pointsales` DEFAULT CHARACTER SET utf8 ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Estado` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NOT NULL,
  `Descripcion` VARCHAR(255) NOT NULL,
  `FechaCreacion` DATETIME NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Categoria` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NOT NULL,
  `Descripcion` VARCHAR(255) NOT NULL,
  `Codigo` VARCHAR(45) NOT NULL,
  `FechaCreacion` DATETIME NOT NULL,
  `Estado` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Categoria_Estado_idx` (`Estado` ASC) VISIBLE,
  CONSTRAINT `fk_Categoria_Estado`
    FOREIGN KEY (`Estado`)
    REFERENCES `ecommerce`.`Estado` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Marca` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NOT NULL,
  `Descripcion` VARCHAR(255) NOT NULL,
  `FechaCreacion` DATETIME NOT NULL,
  `Estado` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Marca_Estado1_idx` (`Estado` ASC) VISIBLE,
  CONSTRAINT `fk_Marca_Estado1`
    FOREIGN KEY (`Estado`)
    REFERENCES `ecommerce`.`Estado` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Descuento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Descuento` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NOT NULL,
  `Codigo` VARCHAR(255) NOT NULL,
  `ValorPorcentaje` DECIMAL(10) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`Producto` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(225) NOT NULL,
  `PrecioVenta` DECIMAL(10) NOT NULL,
  `Stock` INT NOT NULL,
  `PrecioCompra` DECIMAL(10) NOT NULL,
  `Imagen` TEXT(1000) CHARACTER SET 'armscii8' NOT NULL,
  `FechaCreacion` DATETIME NOT NULL,
  `Estado` INT NOT NULL,
  `Marca` INT NOT NULL,
  `Categoria` INT NOT NULL,
  `Descuento` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Producto_Estado1_idx` (`Estado` ASC) VISIBLE,
  INDEX `fk_Producto_Marca1_idx` (`Marca` ASC) VISIBLE,
  INDEX `fk_Producto_Categoria1_idx` (`Categoria` ASC) VISIBLE,
  INDEX `fk_Producto_Descuento1_idx` (`Descuento` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Estado1`
    FOREIGN KEY (`Estado`)
    REFERENCES `ecommerce`.`Estado` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Marca1`
    FOREIGN KEY (`Marca`)
    REFERENCES `ecommerce`.`Marca` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Categoria1`
    FOREIGN KEY (`Categoria`)
    REFERENCES `ecommerce`.`Categoria` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Descuento1`
    FOREIGN KEY (`Descuento`)
    REFERENCES `ecommerce`.`Descuento` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `pointsales` ;

-- -----------------------------------------------------
-- Table `pointsales`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pointsales`.`category` (
  `id_category` INT(11) NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pointsales`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pointsales`.`status` (
  `id_status` INT(11) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pointsales`.`loss`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pointsales`.`loss` (
  `id_loss` INT(11) NOT NULL AUTO_INCREMENT,
  `dateloss` DATETIME NULL DEFAULT NULL,
  `id_status` INT(11) NOT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_loss`),
  INDEX `FK_loss_cState` (`id_status` ASC) VISIBLE,
  CONSTRAINT `loss_ibfk_1`
    FOREIGN KEY (`id_status`)
    REFERENCES `pointsales`.`status` (`id_status`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pointsales`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pointsales`.`product` (
  `id_product` INT(11) NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `product_code` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL,
  `id_status` INT(11) NULL DEFAULT NULL,
  `dateproduct` DATETIME NULL DEFAULT NULL,
  `product_value` DECIMAL(10,2) NULL DEFAULT NULL,
  `product_cost` DECIMAL(10,2) NULL DEFAULT NULL,
  `discount` DECIMAL(10,2) NULL DEFAULT 0.00,
  `stock` INT(11) NULL DEFAULT NULL,
  `id_category` INT(11) NULL DEFAULT NULL,
  `image` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id_product`),
  INDEX `IX_product` (`product_code` ASC) VISIBLE,
  INDEX `FK_product_cState` (`id_status` ASC) VISIBLE,
  INDEX `id_category` (`id_category` ASC) VISIBLE,
  CONSTRAINT `product_ibfk_1`
    FOREIGN KEY (`id_category`)
    REFERENCES `pointsales`.`category` (`id_category`),
  CONSTRAINT `product_ibfk_2`
    FOREIGN KEY (`id_status`)
    REFERENCES `pointsales`.`status` (`id_status`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pointsales`.`loss_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pointsales`.`loss_detail` (
  `id_loss_detail` INT(11) NOT NULL AUTO_INCREMENT,
  `id_loss` INT(11) NULL DEFAULT NULL,
  `unit_cost` DECIMAL(10,2) NULL DEFAULT NULL,
  `id_product` INT(11) NULL DEFAULT NULL,
  `quantity` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_loss_detail`),
  INDEX `FK_loss_detail_loss` (`id_product` ASC) VISIBLE,
  INDEX `FK_loss_detail_loss1` (`id_loss` ASC) VISIBLE,
  CONSTRAINT `loss_detail_ibfk_1`
    FOREIGN KEY (`id_product`)
    REFERENCES `pointsales`.`product` (`id_product`),
  CONSTRAINT `loss_detail_ibfk_2`
    FOREIGN KEY (`id_loss`)
    REFERENCES `pointsales`.`loss` (`id_loss`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pointsales`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pointsales`.`supplier` (
  `id_supplier` INT(11) NOT NULL AUTO_INCREMENT,
  `supplier_name` VARCHAR(75) NULL DEFAULT NULL,
  `address` VARCHAR(150) NULL DEFAULT NULL,
  `telephone` VARCHAR(15) NULL DEFAULT NULL,
  `contact` VARCHAR(75) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `website` VARCHAR(75) NULL DEFAULT NULL,
  PRIMARY KEY (`id_supplier`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pointsales`.`purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pointsales`.`purchase` (
  `id_purchase` INT(11) NOT NULL AUTO_INCREMENT,
  `datepurchase` DATETIME NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  `id_status` INT(11) NULL DEFAULT NULL,
  `id_supplier` INT(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_purchase`),
  INDEX `FK_entrada_cState` (`id_status` ASC) VISIBLE,
  INDEX `id_supplier` (`id_supplier` ASC) VISIBLE,
  CONSTRAINT `purchase_ibfk_1`
    FOREIGN KEY (`id_supplier`)
    REFERENCES `pointsales`.`supplier` (`id_supplier`),
  CONSTRAINT `purchase_ibfk_2`
    FOREIGN KEY (`id_status`)
    REFERENCES `pointsales`.`status` (`id_status`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pointsales`.`purchase_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pointsales`.`purchase_detail` (
  `id_purchase_detail` INT(11) NOT NULL AUTO_INCREMENT,
  `id_purchase` INT(11) NULL DEFAULT NULL,
  `unit_cost` DECIMAL(10,0) NULL DEFAULT NULL,
  `quantity` INT(11) NULL DEFAULT NULL,
  `id_product` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_purchase_detail`),
  INDEX `FK_detail_entrada_product` (`id_product` ASC) VISIBLE,
  INDEX `FK_detail_entrada_entrada` (`id_purchase` ASC) VISIBLE,
  CONSTRAINT `purchase_detail_ibfk_1`
    FOREIGN KEY (`id_purchase`)
    REFERENCES `pointsales`.`purchase` (`id_purchase`),
  CONSTRAINT `purchase_detail_ibfk_2`
    FOREIGN KEY (`id_product`)
    REFERENCES `pointsales`.`product` (`id_product`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pointsales`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pointsales`.`sales` (
  `id_sales` INT(11) NOT NULL AUTO_INCREMENT,
  `sales_price` DECIMAL(10,2) NULL DEFAULT NULL,
  `sales_discount` DECIMAL(10,2) NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  `datesales` DATETIME NULL DEFAULT NULL,
  `id_status` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_sales`),
  INDEX `sales_ibfk_1` (`id_status` ASC) VISIBLE,
  CONSTRAINT `sales_ibfk_1`
    FOREIGN KEY (`id_status`)
    REFERENCES `pointsales`.`status` (`id_status`))
ENGINE = InnoDB
AUTO_INCREMENT = 160
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pointsales`.`sales_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pointsales`.`sales_detail` (
  `id_sales_detail` INT(11) NOT NULL AUTO_INCREMENT,
  `id_sales` INT(11) NULL DEFAULT NULL,
  `unit_cost` DECIMAL(10,2) NULL DEFAULT NULL,
  `unit_value` DECIMAL(10,2) NULL DEFAULT NULL,
  `quantity` INT(11) NULL DEFAULT NULL,
  `discount` DECIMAL(10,2) NULL DEFAULT 0.00,
  `item_total` DECIMAL(10,2) NULL DEFAULT 0.00,
  `id_product` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_sales_detail`),
  INDEX `sales_detail_ibfk_1` (`id_sales` ASC) VISIBLE,
  INDEX `sales_detail_id_productfk_1` (`id_product` ASC) VISIBLE,
  CONSTRAINT `sales_detail_ibfk_1`
    FOREIGN KEY (`id_sales`)
    REFERENCES `pointsales`.`sales` (`id_sales`),
  CONSTRAINT `sales_detail_id_productfk_1`
    FOREIGN KEY (`id_product`)
    REFERENCES `pointsales`.`product` (`id_product`))
ENGINE = InnoDB
AUTO_INCREMENT = 708
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pointsales`.`sec_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pointsales`.`sec_users` (
  `login` VARCHAR(255) NOT NULL,
  `pswd` VARCHAR(255) NOT NULL,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `active` VARCHAR(1) NULL DEFAULT NULL,
  `activation_code` VARCHAR(32) NULL DEFAULT NULL,
  `priv_admin` VARCHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`login`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `pointsales` ;

-- -----------------------------------------------------
-- Placeholder table for view `pointsales`.`vdetailsales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pointsales`.`vdetailsales` (`name` INT, `unit_value` INT, `quantity` INT, `id_sales` INT);

-- -----------------------------------------------------
-- View `pointsales`.`vdetailsales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pointsales`.`vdetailsales`;
USE `pointsales`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `pointsales`.`vdetailsales` AS select `pointsales`.`product`.`product_name` AS `name`,`pointsales`.`sales_detail`.`unit_value` AS `unit_value`,`pointsales`.`sales_detail`.`quantity` AS `quantity`,`pointsales`.`sales_detail`.`id_sales` AS `id_sales` from (`pointsales`.`sales_detail` join `pointsales`.`product` on(`pointsales`.`sales_detail`.`id_product` = `pointsales`.`product`.`id_product`));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
